### ISSUE TITLE
Missing NextJS

### ISSUE THREAD

**Issue by ndelangen** [zeit/art#9]
Please add the resources for NextJS ?

**Comment by PerStirpes** [comment]
You probably already know this but for the benefit of future others Visit: https://zeit.co and right click on the ▲ logo to access Zeit's style guide. Towards the bottom of the style is where you'll find the NextJS stuff. 

![](https://res.cloudinary.com/zeit-inc/image/upload/front/logos/next-black.png)

![](https://res.cloudinary.com/zeit-inc/image/upload/front/logos/next-white.png)

**Comment by ndelangen** [comment]
Thanks!!
